- problem/swap.py
> Created swap.py

- problem/fibonacci_sequence.py
> Added a fibonacci sequence program

- problem/math_calc.py
Accept the pull request please
> Created math_calc.py

- problem/CompoundInterest.py
> CompoundInterest.py added by Rohan

- problem/Palindrome.py
To check the input/Entered Number is Palindrome or Not.
> Palindrome

- maxprofit.py
> created a file named maxprofit and wrote code

- problem/quadraticeqn.py
> created a file quadraticeqn.py and wrote code

- problem/StockSpan.py
This is a financial problem which is based on stack operation. In this we need to find span of stocks across 'n' days.
> Stock Span Problem based on python

- problem/Convert_Binary_to_Dec.py
- problem/Convert_Dec_to_Binary.py
These two programs are based on bit-manipulation
> Added two basic python programs issue #4

- Basic Addition
- MergeSort.py
I have changed this program to merge sort program.
> Update and rename Basic Addition to MergeSort.py

- Health Management System/Source_code.py
Mini Project on Health management System In Python.
> Issue #4 | Added Health management System Project

- Competitive_program/A. Casimir's String Solitaire.py
- Competitive_program/Caimir's_String_Solitaire.txt
- Guess_the_number_game.py
- Keyboard Program.py
- addition_of_sparse_matrix.py
- addition_program_python.py
- rearranging_a_string.py
Added python code to add all the numbers specified by user
> Initial commit

- Best_Time_to_buy_and_sell_Stocks.py
- Bubble_Sort.py
- Check_Palindrome.py
- Check_Prime.py
- Climbing_Stairs.py
- Climbing_Stairs.txt
- Coin_change_problem.py
- Coin_change_problem.txt
- Factorial.py
- Fibonacci.py
- Largest_Number_of_three.py
- Longest_Common_Prefix.py
- Longest_Common_Prefix.txt
- Max_Subarray.py
- Max_Subarray.txt
- Merge_Two_Sorted_Lists.py
- Merge_Two_Sorted_Lists.txt
- PalindromeNumber.py
- PalindromeNumber.txt
- ReverseInteger.py
- ReverseInteger.txt
- String_Reverse.py
- Two Sum.py
- TwoSum.txt
- Valid_Parentheses.py
- Valid_Parentheses.txt
Added competitive programming questions with answers
> Competitive Coding with Python

- Best_Time_to_buy_and_sell_Stocks.py
- Bubble_Sort.py
- Check_Palindrome.py
- Check_Prime.py
- Climbing_Stairs.py
- Climbing_Stairs.txt
- Coin_change_problem.py
- Coin_change_problem.txt
- Factorial.py
- Fibonacci.py
- Largest_Number_of_three.py
- Longest_Common_Prefix.py
- Longest_Common_Prefix.txt
- Max_Subarray.py
- Max_Subarray.txt
- Merge_Two_Sorted_Lists.py
- Merge_Two_Sorted_Lists.txt
- PalindromeNumber.py
- PalindromeNumber.txt
- ReverseInteger.py
- ReverseInteger.txt
- String_Reverse.py
- Two Sum.py
- TwoSum.txt
- Valid_Parentheses.py
- Valid_Parentheses.txt
Added basic Python programs for Hacktoberfest
> Basic python programs

- Competitive_program/CheckIfArrayPairsAreDivisibleByK.py
Added The code for ```Check If Array Pairs Are Divisible by k``` 
for issue #16 
This pull request adds a new Python module to solve the problem of checking if array pairs are divisible by a given integer `k`. The solution includes a class with a method to perform the check and test cases to validate the implementation.
Key changes:
* Added a new file `Competitive_program/CheckIfArrayPairsAreDivisibleByK.py` containing the problem statement, solution, and test cases. 
Please accept this as a part of Hacktober fest contribution @jayadevvasudevan
> Check If Array Pairs Are Divisible by k

- problem/Threesum.py
> Added Three sum problem

- Fibonacci.py
I added a code snippet to the Fibonacci.py file to generate Fibonacci numbers using the recursive method.
> Updated Fibonacci.py file using recursive method

- Argument_Addition.py
- Complex_Number.py
- Floating_Number_Addition.py
- Integer_Addition.py
- List_Element_Sum.py
- List_Elementwise_Addition.py
- Matrix_Addition.py
- Strings_Concetenation.py
Different ways of addition programs
> Addition_Programs

- TurtleCrossingGame/car_manager.py
- TurtleCrossingGame/main.py
- TurtleCrossingGame/player.py
- TurtleCrossingGame/scoreboard.py
- file handling/basics/main.py
- file handling/basics/sample.txt
- file handling/problems/article.txt
- file handling/problems/countOccurences.py
- file handling/problems/countUppercase.py
- file handling/problems/countlines.py
- file handling/problems/countlines2.py
- file handling/problems/poetry.txt
This is a basic turtle crossing game made using turtle graphics library in python.
Kindly add this under Hacktoberfest 24
> Added Turtle Crossing Game Project

- file handling/basics/main.py
- file handling/basics/sample.txt
- file handling/problems/article.txt
- file handling/problems/countOccurences.py
- file handling/problems/countUppercase.py
- file handling/problems/countlines.py
- file handling/problems/countlines2.py
- file handling/problems/poetry.txt
Added some file handling programs explaining basic syntax and also some problems. 
This fixes issue #77
> Added File Handling Programs

- Snake Game/food.py
- Snake Game/main.py
- Snake Game/scoreboard.py
- Snake Game/snake.py
Added Snake game project built using turtle graphics.
Please add this under Hacktoberfest 2024
> Added Snake Game Project

- Fibonacci.py
Hey @jayadevvasudevan!
I’ve added the memoization solution for the Fibonacci sequence in my recent pull request. Before accepting it, could you please add the 'Hacktoberfest' and 'Hacktoberfest-accepted' labels? This will help ensure it counts towards Hacktoberfest.
> Add memoization solution to optimize Fibonacci calculation

- Image_Scrapper/main.py
- Image_Scrapper/requirements.txt
- tim_sort.py
> Added Image Scrapper
